# Generated by Django 5.2.7 on 2025-10-08 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'cargo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'departamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('depto', models.CharField(blank=True, max_length=10, null=True)),
                ('comuna', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'direccion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='forma_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'forma_pago',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=45)),
                ('horas_semanales', models.IntegerField()),
            ],
            options={
                'db_table': 'jornada',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
            ],
            options={
                'db_table': 'turno',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.CharField(max_length=45, unique=True)),
                ('fono', models.IntegerField(blank=True, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=45, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'empleado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='cuenta_bancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('banco', models.CharField(max_length=45)),
                ('tipo_cuenta', models.CharField(max_length=45)),
                ('numero_cuenta', models.BigIntegerField()),
                ('correo', models.CharField(blank=True, max_length=45, null=True)),
                ('empleado', models.ForeignKey(db_column='empleado_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='cuentas_bancarias', to='core.empleado')),
            ],
            options={
                'db_table': 'cuenta_bancaria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('detalle_contrato', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('cargo', models.ForeignKey(db_column='cargo_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.cargo')),
                ('departamento', models.ForeignKey(db_column='departamento_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.departamento')),
                ('empleado', models.ForeignKey(db_column='empleado_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.empleado')),
            ],
            options={
                'db_table': 'contrato',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('periodo', models.DateField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('imponible', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('no_imponible', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tributable', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('anticipo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('liquido', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('devengado', models.DateField(blank=True, null=True)),
                ('cierre', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=45)),
                ('contrato', models.ForeignKey(db_column='contrato_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.contrato')),
            ],
            options={
                'db_table': 'liquidacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comprobante', models.CharField(blank=True, max_length=45, null=True)),
                ('estado', models.CharField(max_length=45)),
                ('forma_pago', models.ForeignKey(db_column='forma_pago_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.forma_pago')),
                ('liquidacion', models.ForeignKey(db_column='liquidacion_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pagos', to='core.liquidacion')),
            ],
            options={
                'db_table': 'pago',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='turno_has_jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('jornada', models.ForeignKey(db_column='jornada_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.jornada')),
                ('turno', models.ForeignKey(db_column='turno_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.turno')),
            ],
            options={
                'db_table': 'turno_has_jornada',
                'managed': True,
                'unique_together': {('turno', 'jornada')},
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='turno_has_jornada',
            field=models.ForeignKey(db_column='turno_has_jornada_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.turno_has_jornada'),
        ),
    ]
