# Generated by Django 5.2.7 on 2025-11-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_zonatrabajo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={'managed': True, 'ordering': ['-fecha_inicio'], 'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AddField(
            model_name='contrato',
            name='estado',
            field=models.CharField(choices=[('Vigente', 'Vigente'), ('En firma', 'En firma'), ('Finalizado', 'Finalizado')], default='Vigente', max_length=20),
        ),
        migrations.AddField(
            model_name='contrato',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='contratos/'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo',
            field=models.CharField(choices=[('Indefinido', 'Indefinido'), ('Plazo fijo', 'Plazo fijo'), ('Part-time', 'Part-time'), ('Práctica', 'Práctica')], default='Indefinido', max_length=40),
        ),
    ]
