# Generated by Django 5.2.7 on 2025-11-09 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contrato_options_contrato_estado_contrato_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='turno_has_jornada',
            field=models.ForeignKey(blank=True, db_column='turno_has_jornada_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.turno_has_jornada'),
        ),
    ]
