# Generated by Django 5.2.7 on 2025-11-09 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_contrato_turno_has_jornada'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='zona_trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='core.zonatrabajo'),
        ),
    ]
